[profile.default]
# Solidity compiler settings
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# Source and output directories
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

# Remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Gas reporting and optimization
gas_reports = ["SupplyChain"]
gas_reports_ignore = ["test/**/*"]

# Test configuration
verbosity = 2
fuzz = { runs = 1000, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }

# Network configurations
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# Etherscan API configuration for contract verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }

# Development profile for faster compilation
[profile.dev]
solc = "0.8.24"
optimizer = false
verbosity = 3

# CI profile for comprehensive testing
[profile.ci]
solc = "0.8.24"
optimizer = true
optimizer_runs = 10000
verbosity = 1
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 50 }

# Production profile for deployment
[profile.production]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true
verbosity = 1

# Gas snapshot configuration
[profile.gas-snapshot]
gas_reports = ["*"]
gas_reports_ignore = []

# Formatting settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"

# Documentation settings
[doc]
out = "docs"
title = "Supply Chain Tracking System"
book = "book.toml"
homepage = "https://github.com/your-org/supply-chain-contracts"
ignore = ["test/**/*", "script/**/*"]